# action.yml
name: 'Verify Azure Container Apps ARM Namespace'
branding:
  icon: bell
  color: purple
description: 'This action verifies if your sub still relies on preview ARM namespace for Azure Container Apps (Microsoft.Web)'
inputs:
  azure-client-id:
    description: 'Azure Service Principal (SP) Client Id'
    required: true
  azure-client-secret:
    description: 'Azure Service Principal (SP) Client Secret'
    required: true
  azure-tenant-id:
    description: 'Azure Tenant Id'
    required: true
  azure-subscription-id:
    description: 'Desired Azure Subscription Id'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    AZURE_CLIENT_ID: ${{ inputs.azure-client-id }}
    AZURE_CLIENT_SECRET: ${{ inputs.azure-client-secret }}
    AZURE_TENANT_ID: ${{ inputs.azure-tenant-id }}
    AZURE_SUBSCRIPTION_ID: ${{ inputs.azure-subscription-id }}
